# Generated by Django 3.0.7 on 2020-06-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_marcas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='TiposCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de combustible',
                'verbose_name_plural': 'Tipos de combustibles',
            },
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='tiposvehiculos',
            options={'verbose_name': 'Tipo de vehiculo', 'verbose_name_plural': 'Tipos de vehiculos'},
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('chasis', models.IntegerField()),
                ('motor', models.IntegerField()),
                ('placa', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Marcas')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Modelo')),
                ('tipo_de_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.TiposCombustible')),
                ('tipo_de_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.TiposVehiculos')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Marcas'),
        ),
    ]
