# Generated by Django 3.0.7 on 2020-06-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20200608_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('tarejeta_de_credito', models.IntegerField()),
                ('limite_de_credito', models.IntegerField()),
                ('tipo_de_persona', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('tanda_labor', models.CharField(max_length=100)),
                ('comision', models.IntegerField()),
                ('fecha_de_ingreso', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
