# Generated by Django 3.0.7 on 2020-06-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_clientes_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ralladura', models.BooleanField(default=False)),
                ('rotura_de_cristal', models.BooleanField(default=False)),
                ('goma_de_repuesto', models.BooleanField(default=False)),
                ('tiene_gato', models.BooleanField(default=False)),
                ('cantidad_de_combuestible', models.FloatField()),
                ('estado_de_gomas', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(verbose_name='fecha inspeccion')),
                ('estado', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Clientes')),
                ('empleado_de_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Empleados')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Vehiculos')),
            ],
            options={
                'verbose_name': 'Inspeccion',
                'verbose_name_plural': 'Inspecciones',
            },
        ),
    ]
