# Generated by Django 3.0.7 on 2020-06-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_inspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='limite_de_credito',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tarejeta_de_credito',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='comision',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='chasis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='motor',
            field=models.CharField(max_length=100),
        ),
    ]
