# Generated by Django 3.0.7 on 2020-06-13 01:40

import App1.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_renta_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='cantidad_de_combuestible',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='cantidad_de_combustible',
            field=models.CharField(choices=[('25%', '1/4'), ('50%', '1/2'), ('75%', '3/4'), ('100%', 'Full')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renta_devolucion',
            name='numero_renta',
            field=models.CharField(default=App1.models.generar_numero_renta, max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='imagen_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Cedula y guiones Ex:(001-0000000-1)', regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='limite_de_credito',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tarejeta_de_credito',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_de_persona',
            field=models.CharField(choices=[('Jur', 'Juridica'), ('Fis', 'Fisica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Cedula y guiones Ex:(001-0000000-1)', regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_de_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='tanda_labor',
            field=models.CharField(choices=[('Mat', 'Matutina'), ('Ves', 'Vespertina'), ('Noc', 'Nocturna')], max_length=3),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='renta_devolucion',
            name='cantidad_de_Dia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='renta_devolucion',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renta_devolucion',
            name='fecha_de_Devuelta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renta_devolucion',
            name='fecha_de_Renta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='renta_devolucion',
            name='monto_por_dia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='chasis',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='motor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='placa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
