# Generated by Django 3.0.7 on 2020-06-16 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_auto_20200614_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta_devolucion',
            name='fecha_de_Devuelta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
