# Generated by Django 3.0.7 on 2020-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_auto_20200616_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta_devolucion',
            name='fecha_de_Devuelta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
