# Generated by Django 3.0.7 on 2020-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_auto_20200616_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
