# Generated by Django 3.0.7 on 2020-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_auto_20200616_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta_devolucion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
