# Generated by Django 3.0.7 on 2020-06-17 00:43

import App1.Validaciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_auto_20200616_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta_devolucion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Vehiculos', validators=[App1.Validaciones.validar_vehiculo_rentado]),
        ),
    ]
