# Generated by Django 3.0.7 on 2020-06-17 01:03

import App1.Validaciones
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_auto_20200616_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[App1.Validaciones.validar_digito_verificador, django.core.validators.RegexValidator(message='Cedula y guiones Ex:(001-0000000-1)', regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[App1.Validaciones.validar_digito_verificador, django.core.validators.RegexValidator(message='Cedula y guiones Ex:(001-0000000-1)', regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
    ]
